services:
  postgres:
    image: postgres:16
    container_name: dev-postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shahin
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: haq@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres

  mysql:
    image: mysql:latest
    container_name: dev-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    container_name: dev-phpmyadmin-container
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '8181:80'
    depends_on:
      - mysql

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    ports:
      - '27017:21017'

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
